### ISSUE TITLE
[test] set up sanity test

### ISSUE THREAD

**Issue by andyzhangx** [csi-driver/blobfuse-csi-driver#10]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

could refer to https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/test/sanity

**Describe alternatives you've considered**

**Additional context**

**Comment by tall49er** [comment]
Working on it.

**Comment by andyzhangx** [comment]
BTW, what's your slack id, and you could join slack@kubernetes, and then we could talk in that workspace.
@tall49er

**Comment by tall49er** [comment]
My slack id is Rui Tang.

**Comment by tall49er** [comment]
Where can I find azure.json?

**Comment by lizebang** [comment]
@tall49er 
Hi, thank for your participation. You can get azure.json by following the steps below:
1. Create an azure account and apply for a trial.
2. Create a kubernetes cluster and azure.json path is `/etc/kubernetes/azure.json`.

**Comment by andyzhangx** [comment]
actually sanity test is already set up, need to fix the 6 failures: https://github.com/csi-driver/blobfuse-csi-driver/issues/28
