### ISSUE TITLE
Add version flag in blobfuse driver

### ISSUE THREAD

**Issue by andyzhangx** [csi-driver/blobfuse-csi-driver#26]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

could refer to https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/70
This feature is a must for v0.1.0-alpha release

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
hi @ashishranjan738 could you work on this? Thanks.

**Comment by ashishranjan738** [comment]
Sure

**Comment by andyzhangx** [comment]
hi @ashishranjan738 do you have time to work on this? I would like to cut a release when this issue resolved, thanks.

**Comment by ashishranjan738** [comment]
Yeah i can raise today
