### ISSUE TITLE
reduce vendor size

### ISSUE THREAD

**Issue by andyzhangx** [csi-driver/blobfuse-csi-driver#6]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

could refer to https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/64

**Describe alternatives you've considered**

**Additional context**

**Comment by tall49er** [comment]
Can I work on it?

**Comment by andyzhangx** [comment]
sure.
/assign @tall49er
