### ISSUE TITLE
add "dep ensure" check in CI test

### ISSUE THREAD

**Issue by andyzhangx** [csi-driver/blobfuse-csi-driver#7]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

could refer to https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/65

**Comment by tall49er** [comment]
Working on it

**Comment by tall49er** [comment]
CI always failed when I add dep check alone. So in #16 I add dep check after reducing vendor size.

**Comment by tall49er** [comment]
This issue cloud also be closed.#16 has fixed it.

**Comment by andyzhangx** [comment]
thanks. how do you @tall49er find this project?

**Comment by tall49er** [comment]
I am applying for GSoC. I find this project on Kubernetes project idea list. You could review my proposal for this project and give my some advices. Thanks.
https://docs.google.com/document/d/1xUXDJufTKWGWxMA2bVBDWjX-7vv2E21GXAP1QM_adUk/edit?usp=sharing

**Comment by tall49er** [comment]
What about other two projects about AzureFile and AzureDisk? I only apply for Blobfuse. Could you please get me involved in any one of these projects. I will much appreciate that.

**Comment by andyzhangx** [comment]
@tall49er those two projects have assignees already.

**Comment by tall49er** [comment]
Could you please apply for additional headcount for this project?

**Comment by andyzhangx** [comment]
@tall49er I am not familiar with GSOC, is there any exception for this rule?

**Comment by tall49er** [comment]
Yes, since this project need to have more development resources. You could probably get in contact with Kubernetes community and asking for more headcount.
