### ISSUE TITLE
Add boilerplate checking 

### ISSUE THREAD

**Issue by andyzhangx** [csi-driver/blobfuse-csi-driver#8]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

could refer to https://github.com/kubernetes/cloud-provider-azure/pull/106

**Describe alternatives you've considered**

**Additional context**

**Comment by tall49er** [comment]
Can I work on it?

**Comment by andyzhangx** [comment]
@tall49er Have you singed the CLA? If not, please follow instructions at https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ to sign the CLA.

**Comment by tall49er** [comment]
I forgot to sign it, and now I've signed it.

**Comment by andyzhangx** [comment]
@tall49er can you also fix this issue in azuredisk & azurefile csi driver?
https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/59
https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/45
Let  me add you as collabrator first.

**Comment by tall49er** [comment]
sure!
